apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cerebro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: yannart/cerebro
        ports:
        - containerPort: 9000