apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: elasticsearch
  labels:
    app: elasticsearch
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - image: gcr.io/elasticsearch-on-k8s-sample/elasticsearch6:6.3
        name: elasticsearch-master
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "NUMBER_OF_MASTERS"
          value: "1"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: "storage"
        emptyDir:
          medium: ""