apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  serviceName: es-cluster
  replicas: 3
  selector:
    matchLabels:
      service: elasticsearch
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      initContainers:
      - name: fix-the-volume-permission
        image: busybox:1.27.2
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-the-vm-max-map-count
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        env:
#        - name: NAMESPACE
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
#        - name: NODE_NAME
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#        - name: CLUSTER_NAME
        - name: cluster.name
          value: elasticsearch
#        - name: NUMBER_OF_MASTERS
#          value: "2"
#        - name: NODE_MASTER
#          value: "true"
#        - name: NODE_INGEST
#          value: "true"
#        - name: NODE_DATA
#          value: "true"
#        - name: ES_JAVA_OPTS
#          value: -Xms256m -Xmx256m
#        - name: DISCOVERY_SERVICE
        - name: discovery.zen.ping.unicast.hosts
          value: es-cluster
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 2Gi
        ports:
        - containerPort: 9300
          name: tcp
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: elasticsearch-ssd
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi